name: 'Generate Mermaid Diagrams'
description: 'Generates SVG diagrams from changed files using the minlag/mermaid-cli Docker image.'

inputs:
  changed-files:
    description: 'A space-separated string of changed .mmd or .md files.'
    required: true
  output-dir:
    description: "Optional. The directory to place generated files. If not set, creates an 'auto_generated' folder in each source file's directory."
    required: false
  version:
    description: 'The minlag/mermaid-cli docker image version (tag).'
    required: false
    default: 'latest'
  icon-packages:
    description: 'Icon packages to pass to the mmdc --iconPacks flag.'
    required: false
    default: '@fortawesome/fontawesome-free'
  puppeteer-config:
    description: 'Path to the puppeteer config file.'
    required: false
    default: 'puppeteer-config.json'

runs:
  using: 'docker'
  image: 'Dockerfile'
